# Included at the end of the generated variant.cmake (configs id: cmake), once
# the component libraries exist. Everything Zephyr-specific that is not a component.
set(ZEPHYR_APP_SRC ${CMAKE_CURRENT_LIST_DIR}/app/src)

# SPLed's platform toolchain files supply this: `static` in a product build,
# empty in a test build so the tests can reach internal functions.
zephyr_compile_definitions(SPLE_TESTABLE_STATIC=static)

# The product features are generated by KConfigGen into <build>/kconfig, from the product model and
# the variant's selection; Zephyr's own autoconf.h holds only Zephyr's symbols and reaches every
# translation unit through -imacros. main.c is compiled by Zephyr's `app` target rather than as a
# yanga component, so it needs that directory named here to find "autoconf.h".
zephyr_include_directories(${CMAKE_BINARY_DIR}/kconfig)
# Zephyr requires at least one source on `app`; the adapters are yanga components.
target_sources(app PRIVATE ${ZEPHYR_APP_SRC}/main.c)
